### PR TITLE
Remove type equalities repetition

### PR DESCRIPTION
**Pull request by xhtmlboi**
It does not affect YOCaml so much. 
I guess that commit message are sufficient for motivation and explanation.

### CODE REVIEW

**Comment by xvw** [comment]
Before reviewing meticulously, could you add an entry in CHANGE?

**Comment by gr-im** [comment]
Thank you very much for this contribution! I am very much in favour of both commits!
The first, which removes a somewhat unnecessary redundancy, and which is no longer really implemented in the new modules. For example, for Clown, Joker, Kleisli and Cokleisli, I did not put the signature in the `ml`. So IMHO it brings consistency!

About the second commit, and `polarities`. The reason I didn't include it (well, removed it) in `Covariant` is mainly because I had already done Arrow without worrying about variance and didn't want to introduce inconsistency (and make the PR too long). As you mention in your "long" commit message, now Preface can reject : 

```ocaml 
module L = Preface.Make.Functor.Via_map (struct 
   type 'a t = 'a -> bool 
   let map _ _ = assert false
end)
```
But is that really ... good? In fact, implementing map for `a -> bool` seems complicated. Which brings me to my first concern: `type +'a t = A : 'a t | B : int -> 'a t` is valid (because `'a` is covariant` here) but not `type +'a t = A: 'a t | B : int t`, because `'a` is covariant on the first branch but bivariant in the second one) so I guess that my example is artificial like yours but it seems that having explicit variance anotation can lead to ... unexprimable concretisation of abstraction.

**Comment by xhtmlboi** [comment]
@gr-im, If you can give me an example where variance anotations are annoying (or even blocking), I will revert the last commit. Not that I doubt you, but that I'm not sure that "potential improvement" should be blocked for theoretical ideas ;)

**Comment by gr-im** [comment]
```ocaml
module Compact_array : sig type +'a t end = struct
  type +_ t =
    | Bytes : bytes -> char t
    | Other : 'a array -> 'a t
end
```

**Review by xvw — APPROVED** [review]
Thanks and sorry for ... polarity 🥇

**Review by gr-im — APPROVED** [review]

**Pull request merged**
