### PR TITLE
More comonads

### PR DESCRIPTION
**Pull request by gr-im**
Add Store, Env and Traced

If this branch is merged, the documentation must be regenerated

### CODE REVIEW

**Review by xvw — DISMISSED** [review]
Thanks (don't worry, when it is merged, I'll regenerate the documentation ;) )

**Comment by xhtmlboi** [comment]
Generic Transformer has usually an additional combinator:
- `lift` for promoting from Monad
- `lower` for comonads.

**Comment by gr-im** [comment]
@xhtmlboi 
Right.

**Comment by gr-im** [comment]
The two last commits introduces lower for Comonad and upper for Monad.

**Comment by xhtmlboi** [comment]
I have no particular problem with `upper` but the convention is to use `lift`?

**Comment by gr-im** [comment]
Lift was used in Applicative and Monad, it's quite annoying, so we decided to use promote for Free Applicative / Selective, perform for Free / Freer and here ... upper. I think a short term solution would be to rename liftX to mapX and use lift in Free and transform them but not being convinced I preferred to leave that to another PR.

**Review by xhtmlboi — APPROVED** [review]

**Review by xvw — APPROVED** [review]

**Review by d-plaindoux — APPROVED** [review]
Really appreciate the traced_dependencies example.

**Pull request merged**
