### PR TITLE
Indexed modules

### PR DESCRIPTION
**Pull request by mspwn**
This branch adds support for indexed structures (especially useful for `('a, 'b) result`). 
There is still `Traversable` to index (but I still have to think a bit about the design). In principle, only a few cases, the QCheck generators, have to be repeated.

I'm doing an initial PR to get feedback, especially on module strengthening.

### CODE REVIEW

**Comment by gr-im** [comment]
Hi @mspwn! Thanks a lot for your contribution!
I'm currently re-reading it and I quite agree with you, duplicating the `preface_qcheck` modules doesn't seem dramatic to me! However, regarding the `Result` module, I think you can drop `Mono` (even if the idea is good) and just describe `Try` using the `Result` implementation. As we are already in a `breaking-change` version, it might not be a problem!

At the moment, I am doing some experiments with @xvw to see if it is possible to simplify some of the strengthening cases and I will get back to you as soon as possible. Thanks in any case, it's a necessary improvement!

**Comment by mspwn** [comment]
Yes, I'm currently making some experiments about _strengthening_ (removing the `type ... t` into submodules). I'll take some time next week.

**Comment by mspwn** [comment]
> I think you can drop Mono (even if the idea is good) and just describe 

I kept the `Mono` module because I plan to start a `Postface` subpackage (as discussed internally) providing a better API.

I think the pullRequest can be reviewed.

**Review by xhtmlboi — APPROVED** [review]
I guess that you want to deal with traversable in an other PR?

**Review by xvw — APPROVED** [review]

**Review by gr-im — APPROVED** [review]

**Pull request merged**
